bpos_flights/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from bpos_flights import views

urlpatterns = [
    url(r'^$', login_required(views.FlightList.as_view()), name="flight-list"),
    url(r'plist/(?P<pk>[-\w]+)/$', login_required(views.PassengerList.as_view()), name="passenger-list"),
    url(r'passenger/add/$', login_required(views.create_flight), name="flight-add"),
    url(r'add/$', login_required(views.create_flightgroup), name="passenger-add"),
    url(r'passenger/(?P<pk>[-\w]+)/update/$', login_required(views.update_flight), name="passenger-update"),
    url(r'passenger/(?P<pk>[-\w]+)/delete/$', login_required(views.FlightDelete.as_view()), name="passenger-delete"),
    url(r'(?P<pk>[-\w]+)/update/$', login_required(views.update_flightgroup), name="flight-update"),
    url(r'(?P<pk>[-\w]+)/$', login_required(views.FlightDetail.as_view()), name="flight-detail"),
    url(r'get_passenger_info', login_required(views.get_passenger_info)),
    url(r'get_filtered_passengers', login_required(views.get_filtered_passengers)),
    url(r'get_filtered_clients', login_required(views.get_filtered_clients))
]

bpos_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bpos_proj import views
from bpos_proj.forms import LoginForm
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

admin.site.site_header = 'BPOS Settings'
admin.site.index_title = "Settings"
admin.site.site_title = "Administration"

urlpatterns = [
    url(r'^$', views.home, name='home-page'),
    url(r'^api/enquiry_data/$', views.get_enquiry_data, name='enquiry-page'),
    url(r'^login/$', auth_view.login, {'template_name': 'registration/login.html', 'authentication_form': LoginForm}, name="login"),
    url(r'^logout/$', auth_view.LogoutView.as_view(next_page=reverse_lazy('login')), name="logout"),
    url(r'^password_reset/$', auth_view.PasswordResetView.as_view(template_name='registration/password_reset.html'), name="password_reset"),
    url(r'^password_reset/done/$', auth_view.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_view.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name="password_reset_confirm"),
    url(r'^reset/done/$', auth_view.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name="password_reset_complete"),
    url(r'^admin/', admin.site.urls),
    url(r'^client-autocomplete/', login_required(views.ClientAutocomplete.as_view()), name="client-autocomplete"),
    url(r'^mgmtdata/', views.mgmtdata, name='mgmtdata'),
    url(r'^enquiries/', include('bpos_enquiries.urls')),
    url(r'^status/', include('bpos_status_report.urls')),
    url(r'^guiderota/', include('bpos_guide_rota.urls')),
    url(r'^flights/', include('bpos_flights.urls')),
    url(r'^payments/', include('bpos_payments.urls')),
    url(r'^hotels/', include('bpos_hotel_reservation.urls'))
]

bpos_flights/models.py
from django.db import models
from bpos_status_report.models import Client, Member
from bpos_airports.models import Airport
from bpos_status_report.models import TITLE
from bpos_alerts.models import Alert

from django_currentuser.middleware import get_current_authenticated_user

from django.utils import timezone

FARE_OPTIONS = (
    ("full", "Full Fare"),
    ("excursion", "Excursion Fare"),
    ("low", "Low Season Discount"),
    ("other", "Other")
)

FLIGHT_CLASS = (
    ("y", "Y CLass"),
    ("j", "J CLass"),
    ("s", "S CLass")
)

FLIGHT_STATUS = (
    ("0", "Not Yet Requested"),
    ("1", "Requested"),
    ("2", "Confirmed"),
    ("3", "Waitlisted"),
    ("4", "Tickets Issued"),
    ("5", "Tickets Sent")
)


# Create your models here.
class Flight(models.Model):
    client = models.ForeignKey(Client)
    passenger = models.ForeignKey(Member)
    title = models.CharField(max_length=10, choices=TITLE)
    full_name = models.CharField("Full Name", max_length=100, blank=False)
    dob = models.DateField("Date of Birth")
    is_student = models.BooleanField("Is Student?")
    fare = models.CharField(max_length=100, choices=FARE_OPTIONS, blank=False, default="full")
    other_fare = models.CharField("Other Fare", max_length=100, blank=True)
    from_place = models.ForeignKey(Airport, related_name="flight_from_place")
    to_place = models.ForeignKey(Airport, related_name="flight_to_place")
    date = models.DateField("Flight Date")
    flight_no = models.CharField("Specific Flight Number", max_length=20, blank=True)
    flight_class = models.CharField("Class", max_length=20, choices=FLIGHT_CLASS)
    status = models.CharField(max_length=100, choices=FLIGHT_STATUS, default="0")
    ttl = models.DateField("TTL", max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.full_name)

    def __init__(self, *args, **kwargs):
        super(Flight, self).__init__(*args, **kwargs)
        self._ori_ttl = self.ttl
        self._ori_status = self.status

    def save(self, *args, **kwargs):
        desc = ""
        update = 0

        if not self._ori_ttl and self.ttl:
            desc = "TTL Added"
            update = 1
        elif self._ori_ttl and self._ori_ttl != self.ttl:
            desc = "TTL Changed"
            update = 1
        else:
            pass

        if self._ori_status and self._ori_status != self.status and self.status not in (0, 4, 5):
            desc = "Flight " + str(FLIGHT_STATUS[int(self.status)][1]) + " for " + str(self.date)
            update = 1
        elif self._ori_status and self._ori_status != self.status and self.status in (4, 5):
            desc = str(FLIGHT_STATUS[int(self.status)][1]) + " for " + str(self.date)
            update = 1
        else:
            pass

        if update:
            alert_data = {
                "client": self.client,
                "doctype": "Flight",
                "changed_by": get_current_authenticated_user(),
                "changed_at": timezone.now(),
                "desc": desc,
                "ttl": self.ttl
            }
            Alert(**alert_data).save()

        super(Flight, self).save(*args, **kwargs)


class FlightGroup(models.Model):
    client = models.ForeignKey(Client)
    pax = models.IntegerField()
    comments = models.TextField(null=True, blank=True)

bpos_flights/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div
from bpos_flights.models import Flight, FlightGroup
from bpos_status_report.models import Member, Client

from dal import autocomplete


class FlightForm(forms.ModelForm):
    class Meta:
        model = Flight
        fields = '__all__'

    passenger = forms.ModelChoiceField(
        queryset=Member.objects.filter().order_by('id'),
        widget=forms.Select(attrs={
            "onChange": 'getPassengerDetails()'}
        )
    )

    full_name = forms.CharField(
        label="Full Name",
        required=True,
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )

    def clean(self):
        super(FlightForm, self).clean()

    def __init__(self, *args, **kwargs):
        super(FlightForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                'client',
                'passenger',
                'title',
                'full_name',
                'is_student',
                css_class='col-xs-4'
            ),
            Div(
                'dob',
                'fare',
                'other_fare',
                'from_place',
                'to_place',
                css_class='col-xs-4'
            ),
            Div(
                'date',
                'flight_no',
                'flight_class',
                'status',
                'ttl',
                css_class='col-xs-4'
            )
        )


class FlightGroupForm(forms.ModelForm):
    client = forms.ModelChoiceField(
        queryset=Client.objects.all(),
        widget=autocomplete.ModelSelect2(url='client-autocomplete')
    )

    class Meta:
        model = FlightGroup
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(FlightGroupForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                'client',
                'pax',
                css_class='col-xs-4'
            ),
            Div(
                'comments',
                css_class='col-xs-6'
            )
        )

bpos_flights/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import DeleteView

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Flight, FlightGroup
from .forms import FlightForm, FlightGroupForm
from bpos_status_report.models import Member, Client

from dateutil.relativedelta import relativedelta
import simplejson


@permission_required('bpos_flights.add_flight')
def create_flight(request):
    if request.method == 'POST':
        form = FlightForm(request.POST)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()

        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        # Initialize the client value and disable others in view
        if request.GET['client']:
            form = FlightForm(initial={"client": request.GET['client']})
        else:
            form = FlightForm()
    return render(request, 'bpos_flights/passenger/passenger_add.html', {
        'form': form,
    })


@permission_required('bpos_flights.change_flight')
def update_flight(request, pk):
    if request.method == 'POST':
        flights = get_object_or_404(Flight, pk=pk)
        form = FlightForm(request.POST, instance=flights)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        flights = get_object_or_404(Flight, pk=pk)
        form = FlightForm(instance=flights)

    return render(request, 'bpos_flights/passenger/passenger_update.html', {
        'form': form,
    })


class FlightDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('bpos_flights.delete_flight')
    model = Flight
    template_name = "common/delete_form.html"

    def post(self, request, *args, **kwargs):
        self.success_url = request.POST['parent_url']
        return self.delete(request, *args, **kwargs)


class FlightList(ListView):
    model = FlightGroup
    template_name = "bpos_flights/flights_list.html"

    def get_context_data(self, **kwargs):
        context = super(FlightList, self).get_context_data(**kwargs)
        for a in context['object_list']:
            fl = Flight.objects.filter(client=a.client).values("ttl").order_by("-ttl")[:1]
            if fl:
                a.ttl = fl[0]['ttl']
        return context


class PassengerList(ListView):
    model = Flight
    template_name = "bpos_flights/passenger/passenger_list.html"

    def get_context_data(self, **kwargs):
        context = super(PassengerList, self).get_context_data(**kwargs)
        pk_id = self.kwargs.get('pk', None)
        if pk_id:
            context['client'] = FlightGroup.objects.get(pk=pk_id)
            context['object_list'] = context['object_list'].filter(client=context['client'].client)
            for a in context['object_list']:
                if(relativedelta(a.date, a.dob).years < 12):
                    a.is_child = 1
                else:
                    a.is_child = 0
        else:
            context['client'] = None
            context['object_list'] = None

        return context


class FlightDetail(DetailView):
    model = Flight
    template_name = "bpos_flights/flights_detail.html"

    def get_context_data(self, **kwargs):
        context = super(FlightDetail, self).get_context_data(**kwargs)
        return context


@permission_required('bpos_flights.add_flightgroup')
def create_flightgroup(request):
    if request.method == 'POST':
        form = FlightGroupForm(request.POST)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        form = FlightGroupForm()

    return render(request, 'bpos_flights/flights_add.html', {
        'form': form,
    })


@permission_required('bpos_flights.change_flightgroup')
def update_flightgroup(request, pk):
    if request.method == 'POST':
        flights = get_object_or_404(FlightGroup, pk=pk)
        form = FlightGroupForm(request.POST, instance=flights)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        flights = get_object_or_404(FlightGroup, pk=pk)
        form = FlightGroupForm(instance=flights)

    return render(request, 'bpos_flights/flights_update.html', {
        'form': form,
    })


# Get the filtered list of clients for on the client filter
def get_filtered_clients(request):
    response = {}
    if request.GET.get('trekking_status'):
        client_obj = request.GET.get('trekking_status')
        if client_obj == '0':
            result = Client.objects.filter().order_by("id")
        else:
            result = Client.objects.filter(trekking_status=client_obj).order_by("id")
    else:
        result = Client.objects.filter().order_by("id")

    for a in result:
        response[a.id] = a.__str__()

    return HttpResponse(simplejson.dumps(response))


# Get the filtered list of passengers based on the client filter
def get_filtered_passengers(request):
    response = {}
    if request.GET.get('client_filter'):
        client_obj = request.GET.get('client_filter')
        if client_obj == '0':
            result = Member.objects.filter().order_by("id")
        else:
            result = Member.objects.filter(client=client_obj).order_by("id")
    else:
        result = Member.objects.filter().order_by("id")

    for a in result:
        response[a.id] = a.__str__()

    return HttpResponse(simplejson.dumps(response))


# Get the Passenger Info
def get_passenger_info(request):
    response = {}
    if request.GET.get('pass_id'):
        client_name = request.GET.get('pass_id')
        result = Member.objects.filter(pk=client_name).values("title", "full_name")
        response['title'] = result[0]['title']
        response['full_name'] = result[0]['full_name']

    return HttpResponse(simplejson.dumps(response))

templates/bpos_flights/passenger/add_hide.html
<script>
		function toggleHide() {
			if(document.getElementById('id_fare').options[document.getElementById('id_fare').selectedIndex].value == "other") {
				document.getElementById("div_id_other_fare").style.display = "inline";
			}
			else {
				document.getElementById("div_id_other_fare").style.display = "none";
			}
			
		}

		window.onload = function() {
       		$('body').on('change', '#id_fare', toggleHide)
    		}
		
	</script>

templates/bpos_flights/passenger/gr_list_datatable.html
{% load staticfiles%}

<script src="{% static 'datatables/DataTables-1.10.16/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'datatables/DataTables-1.10.16/js/dataTables.bootstrap.min.js' %}"></script>
	
	<!-- For dataTables -->
	<script>
	
	$(document).ready( function () {
    		
	    $('#passenger_list').DataTable({});
	    
	    var oTable = $('#passenger_list').dataTable();
	    
	    $('#client-list').on("change", function(e) {
	    		oTable.fnDraw();
	    });
	} );
	
	</script>

templates/bpos_flights/passenger/passenger_add.html
{% load crispy_forms_tags %}

{% block content %}
	<form method="post" class="form" id="custom_dialog_form" >
	  {% include 'common/error_field.html' %}
	 {% crispy form form.helper%}
	</form>
	<script>
		$("#id_date").datepicker({ dateFormat: "yy-mm-dd" });
		$("#id_dob").datepicker({ dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true, yearRange: "-100:+0"});
		$("#id_ttl").datepicker({ dateFormat: "yy-mm-dd" });
		
		//Run the field hide script when document is ready
		$( function() {
			toggleHide();
			getFilteredPassenger();
		})
		
		//Disable other options
		$( "#id_client option:not(:selected)" ).prop('disabled',true);	
	</script>
{% endblock %}

templates/bpos_flights/passenger/passenger_list.html
{% extends 'common/base.html' %}
{% load staticfiles%}
{% load bpos_group_check %}

{% block header %}
    <link href="{% static 'datatables/DataTables-1.10.16/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css" rel="stylesheet">
{% endblock %}

{% block content %}
	<h3> {{ client.client }} - list of pax
		{% if request.user|has_group:"London" or request.user|has_group:"Ticketing" or request.user|has_group:"General Manager" or request.user.is_superuser%}
		<a id='{{ client.client_id }}' class="btn btn-success create_passenger_button" style="float: right; margin-left: 10px;"> Add New </a>
		{% endif %}
		<a href="/flights/" class="btn btn-info" style="float: right; ">  &lt;&lt; Back to Flight List </a>
	</h3>
	<hr />
	
	<div class="table-responsive" style="clear: both;">  
		 <br />
		<table class="table table-hover" id="passenger_list">
			<thead class="thead-light">
				<tr>
					<th>Title</th>
					<th>Name</th>
					<th>From </th>
					<th>To</th>
					<th>Date</th>
					<th>Class</th>
					<th>Status</th>
					<th>TTL</th>
					<th>Student</th>
					<th>Child</th>
					{% if request.user|has_group:"London" or request.user|has_group:"Ticketing" or request.user|has_group:"General Manager" or request.user.is_superuser%}
					<th></th>
					<th></th>
					{% endif %}
				</tr>
			</thead>
			<tbody>
			{% for a in object_list %}
				<tr>
					<td> {{ a.get_title_display }} </td>
					<td> {{ a.full_name }}</td>	
					<td> {{ a.from_place }} </td>
					<td> {{ a.to_place }}</td>
					<td> {{ a.date }}</td>
					<td> {{ a.get_flight_class_display }} </td>
					<td> {{ a.get_status_display }} </td>
					<td> {{ a.ttl }} </td>
					<td> {% if a.is_student %} <i class="fas fa-check"></i> {% else %} {% endif %}</td>
					<td> {% if a.is_child %} <i class="fas fa-check"></i> {% else %} {% endif %} </td>
					{% if request.user|has_group:"London" or request.user|has_group:"Ticketing" or request.user|has_group:"General Manager" or request.user.is_superuser%}
					<td> <a class='edit_passenger' id='{{ a.id }}'><i class="fas fa-edit text-info"></i></a> </td>
					<td> <a class='delete_passenger' id='{{ a.id }}' href="/flights/passenger/{{a.id}}/delete/"><i class="far fa-trash-alt"></i></a> </td>
					{% endif %}
				</tr>
			{% empty %}
				<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
				{% if request.user|has_group:"London" or request.user|has_group:"Ticketing" or request.user|has_group:"General Manager" or request.user.is_superuser%}
				<td></td><td></td>
				{% endif %}
				</tr>
			{% endfor %}
			</tbody>
		</table>

{% endblock %}

{% block footer %}	
	{% include 'bpos_flights/passenger/gr_list_datatable.html' %}
	{% include 'bpos_flights/passenger/add_hide.html' %}
    {% include 'common/create_dialog.html' %}
    
    <!-- Date Picker -->
	<script>
	  $( function() {
	    $("#from_date").datepicker({ dateFormat: "yy-mm-dd" });
	    $("#to_date").datepicker({ dateFormat: "yy-mm-dd" });
	  } );
	</script>
	
    <script>
	    $(function() {
	        $('.create_passenger_button').on('click', function() { 
	            $('#dialog-modal').load('/flights/passenger/add/?client=' + $(this).context.id);
	            init_dialog("Create a New Passenger", "/flights/passenger/add/", "#custom_dialog_form", "Create Passenger")
	            
	        });
	        
	        $('.edit_passenger').on('click', function() { 
	            url = "/flights/passenger/" + $(this).context.id + "/update/"
	            $('#dialog-modal').load(url);
	            init_dialog("Update Passenger", url, "#custom_dialog_form", "Update Passenger")
	        });   
	    });
	    
	    function getPassengerDetails() {
	    		var client = document.getElementById("id_passenger").value;
	    		$.ajax({ 
                url: "/flights/get_passenger_info?pass_id=" + client,
                type: 'get',
                success: function(response) {
                		data = JSON.parse(response);
                    if(data) {
                    		$('#id_title').val(data["title"])
                    		$('#id_full_name').val(data["full_name"])
                    }
                }
	    		})
	    }
	    
	    function getFilteredPassenger() {
	    		var client = document.getElementById("id_client").value;
	    		$.ajax({ 
	            url: "/flights/get_filtered_passengers?client_filter=" + client,
	            type: 'get',
	            success: function(response) {
	            		data = JSON.parse(response);
	                if(data) {
	                		var $select = $('#id_passenger')
	                		$select.empty()
	                		$select.append($("<option></option>").attr("value", '').text("---------"));
						$.each(data, function(key, value) {
							$select.append($("<option></option>")
									.attr("value", key).text(value));
						})	                		
	                }
	            }
	    		})
	    }

	    var d = document.getElementById("flights")
		d.className += "active"
    </script>

{% endblock %}

templates/bpos_flights/passenger/passenger_update.html
{% load crispy_forms_tags %}

{% block content %}
	<form method="post" class="form" id="custom_dialog_form" >
	  {% include 'common/error_field.html' %}
	 {% crispy form form.helper%}
	</form>
	<script>
		$("#id_date").datepicker({ dateFormat: "yy-mm-dd" });
		$("#id_dob").datepicker({ dateFormat: "yy-mm-dd", changeMonth: true, changeYear: true, yearRange: "-100:+0"});
		$("#id_ttl").datepicker({ dateFormat: "yy-mm-dd" });
		
		//Run the field hide script when document is ready
		$( function() {
			toggleHide();
			//getFilteredPassenger();
		})
		
		//Disable other options
		$( "#id_client option:not(:selected)" ).prop('disabled',true);	
	</script>
{% endblock %}