bpos_guide_rota/urls.py
from django.conf.urls import url
from bpos_guide_rota import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^$', login_required(views.GroupGuideList.as_view()), name="guiderota-list"),
    url(r'add/$', login_required(views.create_guiderota), name="guiderota-add"),
    url(r'(?P<pk>[-\w]+)/update/$', login_required(views.update_guiderota), name="guiderota-update"),
    url(r'(?P<pk>[-\w]+)/$', login_required(views.GroupGuideDetail.as_view()), name="guiderota-detail"),
    url(r'^get_client_info', login_required(views.get_client_information), name="guiderota_get_client_information"),
    url(r'^get_filtered_guides', login_required(views.get_filtered_guides), name="guiderota_get_filtered_guides")
]

bpos_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bpos_proj import views
from bpos_proj.forms import LoginForm
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

admin.site.site_header = 'BPOS Settings'
admin.site.index_title = "Settings"
admin.site.site_title = "Administration"

urlpatterns = [
    url(r'^$', views.home, name='home-page'),
    url(r'^api/enquiry_data/$', views.get_enquiry_data, name='enquiry-page'),
    url(r'^login/$', auth_view.login, {'template_name': 'registration/login.html', 'authentication_form': LoginForm}, name="login"),
    url(r'^logout/$', auth_view.LogoutView.as_view(next_page=reverse_lazy('login')), name="logout"),
    url(r'^password_reset/$', auth_view.PasswordResetView.as_view(template_name='registration/password_reset.html'), name="password_reset"),
    url(r'^password_reset/done/$', auth_view.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_view.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name="password_reset_confirm"),
    url(r'^reset/done/$', auth_view.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name="password_reset_complete"),
    url(r'^admin/', admin.site.urls),
    url(r'^client-autocomplete/', login_required(views.ClientAutocomplete.as_view()), name="client-autocomplete"),
    url(r'^mgmtdata/', views.mgmtdata, name='mgmtdata'),
    url(r'^enquiries/', include('bpos_enquiries.urls')),
    url(r'^status/', include('bpos_status_report.urls')),
    url(r'^guiderota/', include('bpos_guide_rota.urls')),
    url(r'^flights/', include('bpos_flights.urls')),
    url(r'^payments/', include('bpos_payments.urls')),
    url(r'^hotels/', include('bpos_hotel_reservation.urls'))
]

bpos_flights/models.py
from django.db import models
from bpos_status_report.models import Client, Member
from bpos_airports.models import Airport
from bpos_status_report.models import TITLE
from bpos_alerts.models import Alert

from django_currentuser.middleware import get_current_authenticated_user

from django.utils import timezone

FARE_OPTIONS = (
    ("full", "Full Fare"),
    ("excursion", "Excursion Fare"),
    ("low", "Low Season Discount"),
    ("other", "Other")
)

FLIGHT_CLASS = (
    ("y", "Y CLass"),
    ("j", "J CLass"),
    ("s", "S CLass")
)

FLIGHT_STATUS = (
    ("0", "Not Yet Requested"),
    ("1", "Requested"),
    ("2", "Confirmed"),
    ("3", "Waitlisted"),
    ("4", "Tickets Issued"),
    ("5", "Tickets Sent")
)


# Create your models here.
class Flight(models.Model):
    client = models.ForeignKey(Client)
    passenger = models.ForeignKey(Member)
    title = models.CharField(max_length=10, choices=TITLE)
    full_name = models.CharField("Full Name", max_length=100, blank=False)
    dob = models.DateField("Date of Birth")
    is_student = models.BooleanField("Is Student?")
    fare = models.CharField(max_length=100, choices=FARE_OPTIONS, blank=False, default="full")
    other_fare = models.CharField("Other Fare", max_length=100, blank=True)
    from_place = models.ForeignKey(Airport, related_name="flight_from_place")
    to_place = models.ForeignKey(Airport, related_name="flight_to_place")
    date = models.DateField("Flight Date")
    flight_no = models.CharField("Specific Flight Number", max_length=20, blank=True)
    flight_class = models.CharField("Class", max_length=20, choices=FLIGHT_CLASS)
    status = models.CharField(max_length=100, choices=FLIGHT_STATUS, default="0")
    ttl = models.DateField("TTL", max_length=100, blank=True, null=True)

    def __str__(self):
        return str(self.full_name)

    def __init__(self, *args, **kwargs):
        super(Flight, self).__init__(*args, **kwargs)
        self._ori_ttl = self.ttl
        self._ori_status = self.status

    def save(self, *args, **kwargs):
        desc = ""
        update = 0

        if not self._ori_ttl and self.ttl:
            desc = "TTL Added"
            update = 1
        elif self._ori_ttl and self._ori_ttl != self.ttl:
            desc = "TTL Changed"
            update = 1
        else:
            pass

        if self._ori_status and self._ori_status != self.status and self.status not in (0, 4, 5):
            desc = "Flight " + str(FLIGHT_STATUS[int(self.status)][1]) + " for " + str(self.date)
            update = 1
        elif self._ori_status and self._ori_status != self.status and self.status in (4, 5):
            desc = str(FLIGHT_STATUS[int(self.status)][1]) + " for " + str(self.date)
            update = 1
        else:
            pass

        if update:
            alert_data = {
                "client": self.client,
                "doctype": "Flight",
                "changed_by": get_current_authenticated_user(),
                "changed_at": timezone.now(),
                "desc": desc,
                "ttl": self.ttl
            }
            Alert(**alert_data).save()

        super(Flight, self).save(*args, **kwargs)


class FlightGroup(models.Model):
    client = models.ForeignKey(Client)
    pax = models.IntegerField()
    comments = models.TextField(null=True, blank=True)

bpos_guide_rota/models.py
from django.db import models

from bpos_status_report.models import Client
from bpos_guides.models import Guide

OPTIONS = (
    ("0", "All Guides"),
    ("3", "Has Trekking Licence "),
    ("2", "No Trekking Licence, but does Trek ")
)


class GroupGuide(models.Model):
    guide_filter = models.CharField(max_length=50, blank=False, choices=OPTIONS, default="0")
    client = models.ForeignKey(Client)
    guide = models.ForeignKey(Guide, null=True, blank=True)
    available = models.BooleanField("Available?")
    confirmed = models.BooleanField("Confirmed?")
    language = models.CharField("Language", max_length=200, blank=True, null=True)
    trek = models.CharField("Trek", max_length=200, blank=True, null=True)

    class Meta:
        permissions = (
            ('change_groupguide_confirmed', 'Change Confirmed of Guide'),
        )

    def save(self, *args, **kwargs):
        if self.confirmed:
            client = Client.objects.get(pk=self.client.id)
            if client.guide:
                match = False
                for a in client.guide.split(","):
                    print(a)
                    if a == self.guide.__str__():
                        match = True
                        break
                if not match:
                    client.guide = (client.guide + " , " + self.guide.__str__())
            else:
                client.guide = self.guide.__str__()
            client.save()

        return super(GroupGuide, self).save(*args, **kwargs)

bpos_guide_rota/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div

from bpos_guide_rota.models import GroupGuide, OPTIONS
from bpos_guides.models import Guide
from bpos_status_report.models import Client
from dal import autocomplete


class GuideRotaForm(forms.ModelForm):
    class Meta:
        model = GroupGuide
        fields = ['guide_filter', 'client', 'guide', 'available', 'confirmed', "language", "trek", "confirmed"]

    trek = forms.CharField(
        required=False,
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )

    language = forms.CharField(
        label="Specific Language Required",
        required=False,
        widget=forms.TextInput(attrs={'readonly': 'readonly'})
    )

    guide_filter = forms.ChoiceField(
        label="Guide Trekking Status",
        choices=OPTIONS,
        widget=forms.Select(attrs={
            "onChange": 'getFilteredGuides()'}
        )
    )

    client = forms.ModelChoiceField(
        queryset=Client.objects.filter().order_by('id'),
        widget=autocomplete.ModelSelect2(url='client-autocomplete',
                                         attrs={
                                             "onChange": 'getClientDetails()'
                                         })
    )

    guide = forms.ModelChoiceField(
        queryset=Guide.objects.filter().order_by('id'),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user')
        if not self.user.has_perm('bpos_guide_rota.change_groupguide_confirmed'):
            pass

        self.helper = FormHelper()
        self.helper.layout = Layout(
            Div(
                'client',
                'language',
                'trek',
                css_class='col-md-6'
            ),
            Div(
                'guide_filter',
                'guide',
                'available',
                'confirmed',
                css_class='col-md-6'
            )
        )

        '''if not self.user.has_perm('bpos_guide_rota.change_groupguide_confirmed'):
            self.helper.layout = Layout(
                Div(
                    'client',
                    'language',
                    'trek',
                    css_class='col-md-6'
                ),
                Div(
                    'guide_filter',
                    'guide',
                    'available',
                    css_class='col-md-6'
                )
            ) '''

        super(GuideRotaForm, self).__init__(*args, **kwargs)

    def clean(self):
        data = super(GuideRotaForm, self).clean()
        if not data.get("available") and data.get("confirmed"):
            raise forms.ValidationError("Cannot be confirmed when Unavailable")

bpos_guide_rota/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import GroupGuide
from .forms import GuideRotaForm
from bpos_status_report.models import Client
from bpos_guides.models import Guide
import simplejson


@permission_required('bpos_guide_rota.add_groupguide')
def create_guiderota(request):
    if request.method == 'POST':
        form = GuideRotaForm(request.POST, user=request.user)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        form = GuideRotaForm(user=request.user)

    return render(request, 'bpos_guide_rota/guiderota_add.html', {
        'form': form,
    })


@permission_required('bpos_guide_rota.change_groupguide')
def update_guiderota(request, pk):
    if request.method == 'POST':
        guiderota = get_object_or_404(GroupGuide, pk=pk)
        form = GuideRotaForm(request.POST, instance=guiderota, user=request.user)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        guiderota = get_object_or_404(GroupGuide, pk=pk)
        form = GuideRotaForm(instance=guiderota, user=request.user)

    return render(request, 'bpos_guide_rota/guiderota_update.html', {
        'form': form,
    })


class GroupGuideList(PermissionRequiredMixin, ListView):
    permission_required = ('bpos_guide_rota.view_groupguide')
    model = GroupGuide
    template_name = "bpos_guide_rota/guiderota_list.html"

    def get_context_data(self, **kwargs):
        context = super(GroupGuideList, self).get_context_data(**kwargs)
        for a in context['object_list']:
            client = Client.objects.get(pk=a.client_id)
            a.start = client.arriving_date
            a.end = client.leaving_date
        return context


class GroupGuideDetail(PermissionRequiredMixin, DetailView):
    permission_required = ('bpos_guide_rota.view_groupguide')
    model = GroupGuide
    template_name = "bpos_guide_rota/guiderota_detail.html"

    def get_context_data(self, **kwargs):
        context = super(GroupGuideDetail, self).get_context_data(**kwargs)
        return context


# Get the trek and other language information of clients
def get_client_information(request):
    response = {}
    if request.GET.get('client_id'):
        client_name = request.GET.get('client_id')
        result = Client.objects.filter(pk=client_name).values("trek", "other_trek", "language", "other_language")

        if result[0]['other_trek']:
            response['trek'] = result[0]['other_trek']
        else:
            response['trek'] = result[0]['trek']

        if result[0]['other_language']:
            response['language'] = result[0]['other_language']
        else:
            response['language'] = result[0]['language']

    return HttpResponse(simplejson.dumps(response))


# Get the filtered list of guides based on the guide filter
def get_filtered_guides(request):
    response = {}
    if request.GET.get('trekking_status'):
        trekking_status = request.GET.get('trekking_status')
        if trekking_status == '0':
            result = Guide.objects.filter().order_by("id")
        else:
            result = Guide.objects.filter(trekking_status=trekking_status).order_by("id")
    else:
        result = Guide.objects.filter().order_by("id")

    for a in result:
        response[a.id] = a.__str__()

    return HttpResponse(simplejson.dumps(response))

templates/bpos_guide_rota/gr_list_datatable.html
{% load staticfiles%}

<script src="{% static 'datatables/DataTables-1.10.16/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'datatables/DataTables-1.10.16/js/dataTables.bootstrap.min.js' %}"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/r-2.2.1/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.16/r-2.2.1/datatables.min.js"></script>
	
	<!-- For dataTables -->
	<script>
	
	$(document).ready( function () {
		//Guide  Filter
		$.ajax({ 
            url: "/guiderota/get_filtered_guides?trekking_status=0",
            type: 'get',
            success: function(response) {
            		data = JSON.parse(response);
                if(data) {
                		var $select = $('#is_monitored')
                		$select.empty()
                		$select.append($("<option></option>").attr("value", '').text("All Guides"));
					$.each(data, function(key, value) {
						$select.append($("<option></option>")
								.attr("value", key).text(value));
					})	                		
                }
            }
    		})
    		
	    $('#guiderota_list').DataTable({
	    		"columnDefs": [
	    			{
	    				"targets": [ 8 ],
	    				"searchable": false,
	    			}
	    		]
	    });
	    
	    //Filtering for is_monitored
	    $.fn.dataTableExt.afnFiltering.push(function(oSettings, aData, iDataIndex) {
	    		var value = $('#is_monitored').find(":selected").text();
	    		if(value == "All Guides") {
	    			return true
	    		}
	    		else if (aData[1] == value) {
	    			return true
	    		}
	    		
	    		return false
	    });
	    
	    $.fn.dataTableExt.afnFiltering.push(
				function( oSettings, aData, iDataIndex ) {
					var iFini = document.getElementById('from_date').value.replace(/\-/g, '');
					var iFfin = document.getElementById('to_date').value.replace(/\-/g, '');
					
					var iStartDateCol = 3;
					var iEndDateCol = 4;
					
					dateini = new Date(aData[iStartDateCol])
					var datofini = dateini.getFullYear() + "" + ('0' + (dateini.getMonth() + 1)).slice(-2) + "" + ('0' + (dateini.getDate())).slice(-2)				
					
					if (iFini === "" && iFfin === "") {
						return true
					}
					else if ( iFini <= datofini && iFfin === "")
					{
						return true;
					}
					else if ( iFfin >= datofini && iFini === "")
					{
						return true;
					}
					else if(iFini <= datofini && iFfin >= datofini) {
						return true
					}
					return false;
				}
			);
	    
	    var oTable = $('#guiderota_list').dataTable();
	    
	    $('#is_monitored').on("change", function(e) {
	    		oTable.fnDraw();
	    });
	    
	    $('#from_date').on("change", function(e) { 
    			oTable.fnDraw(); 
	    	});
	    
	    $('#to_date').on("change", function(e) { 
	    		oTable.fnDraw(); 
	    	});
	} );
	
	</script>

templates/bpos_guide_rota/guiderota_add.html
{% load crispy_forms_tags %}

{% block content %}
	<form method="post" class="form" id="custom_dialog_form" >
	  {% include 'common/error_field.html' %}
	  {% crispy form form.helper %}
	</form>
{% endblock %}

templates/bpos_guide_rota/guiderota_detail.html
{% extends 'common/base.html' %}

{% block content %}
<div style="width: 50% !important; margin-right: auto !important; margin-left: auto !important;">
  <h2 style="text-align: center;">{{ object.full_name }}</h2>
  <table class="table">
    <thead>
      <tr>
        <th>Label</th>
        <th>Value</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><b>First Name</b></td>
        <td>{{ object.first_name }}</td>
      </tr>
      <tr>
        <td><b>Last Name</b></td>
        <td>{{ object.last_name }}</td>
      </tr>
      <tr>
        <td><b>Email</b></td>
        <td>{{ object.email }}</td>
      </tr>
      <tr>
        <td><b>Phone</b></td>
        <td>{{ object.phone }}</td>
      </tr>
      <tr>
        <td><b>Source</b></td>
        <td>{{ object.source }}</td>
      </tr>
      <tr>
        <td><b>Planned Trip</b></td>
        <td>{{ object.planned_trip }}</td>
      </tr>
      <tr>
        <td><b>Status</b></td>
        <td>{{ object.get_status_display }}</td>
      </tr>
      <tr>
        <td><b>Action Taken</b></td>
        <td>{{ object.get_action_taken_display }}</td>
      </tr>
      <tr>
        <td><b>Other Actions</b></td>
        <td>{{ object.other_action }}</td>
      </tr>
      <tr>
        <td><b>Is Monitored</b></td>
        <td>{{ object.is_monitored }}</td>
      </tr>
    </tbody>
  </table>

<a href="/enquiries/{{ object.slug }}/update" class="btn btn-success"> Edit </a>
<a href="/enquiries" class="btn btn-primary"> Back To List </a>
</div>
{% endblock %}

templates/bpos_guide_rota/guiderota_list.html
{% extends 'common/base.html' %}
{% load staticfiles%}
{% load bpos_group_check %}

{% block header %}
    <link href="{% static 'datatables/DataTables-1.10.16/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css" rel="stylesheet">
{% endblock %}

{% block content %}
	<h2>Guide Rota
		{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser%}
			<a id='create_guiderota_button' class="btn btn-success" style="float: right;"> Add New </a>
		{% endif %}
	</h2>
	<hr />
	
	<div class="table-responsive" style="clear: both;">  
		<table border="0" cellspacing="5" cellpadding="5">
       		 <tbody>
       		 	<tr>
     		       <td>Date from &emsp;</td>
   		           <td>
   		           	<div class="input-group mb-3">
   		           		<input type="text" id="from_date" name="from_date" class="textinput textInput form-control input-sm" placeholder="From Date">
					  </div>
					</td>
           		    <td> &emsp;to&emsp; </td>
                    <td><input type="text" id="to_date" name="to_date" class="textinput textInput form-control input-sm" placeholder="To Date"></td>
               </tr>
    			</tbody>
    		</table>
    		<br />
		<table border="0" cellspacing="5" cellpadding="5">
			<tbody>
				<tr>
		            <td>Guide :&emsp;</td>
		            <td><select id="is_monitored" name="is_monitored" class="select form-control input-sm"></select></td>
		        </tr>
		    </tbody>
		</table> <br />
		<table class="table table-hover" id="guiderota_list">
			<thead class="thead-light">
				<tr>
					<th>Client</th>
					<th>Guide</th>
					<th>Language</th>
					<th>Arriving On</th>
					<th>Leaving On</th>
					<th>Trek</th>
					<th>Available?</th>
					<th>Confirmed?</th>
					{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser%}
					<th></th>
					{% endif %}
				</tr>
			</thead>
			<tbody>
			{% for a in object_list %}
				<tr>
					<td> {{ a.client }} </td>
					<td> {% if a.guide %} {{ a.guide }} {% else %} {% endif %}</td>	
					<td> {{ a.language }} </td>
					<td> {{ a.start }}</td>
					<td> {{ a.end }}</td>
					<td> {{ a.trek }} </td>
					<td> {% if a.available %} <i class="fas fa-check"></i> {% else %} {% endif %}</td>
					<td> {% if a.confirmed %} <i class="fas fa-check"></i> {% else %} {% endif %} </td>
					{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser%}
					<td> <a class='edit_guiderota' id='{{ a.id }}'><i class="fas fa-edit text-info"></i></a> </td>
					{% endif %}
				</tr>
			{% empty %}
				<tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td>
				{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser%}
				<td></td>
				{% endif %}</tr>
			{% endfor %}
			</tbody>
		</table>

{% endblock %}

{% block footer %}	
	{% include 'bpos_guide_rota/gr_list_datatable.html' %}
	{% include 'bpos_enquiries/add_hide.html' %}
    {% include 'common/create_dialog.html' %}
    
    <!-- Date Picker -->
	<script>
	  $( function() {
	    $("#from_date").datepicker({ dateFormat: "yy-mm-dd" });
	    $("#to_date").datepicker({ dateFormat: "yy-mm-dd" });
	  } );
	</script>
	
    <script>
	    $(function() {
	        $('#create_guiderota_button').on('click', function() { 
	            $('#dialog-modal').load('/guiderota/add/');
	            init_dialog("Create a New Guide Rota", "add/", "#custom_dialog_form", "Create Guide Rota")
	            
	        });
	        
	        $('.edit_guiderota').on('click', function() { 
	            url = "/guiderota/" + $(this).context.id + "/update/"
	            $('#dialog-modal').load(url);
	            init_dialog("Update Guide Rota", url, "#custom_dialog_form", "Update Guide Rota")
	        });
	        
	    });
	    
	    function getClientDetails() {
	    		var client = document.getElementById("id_client").value;
	    		$.ajax({ 
                url: "/guiderota/get_client_info?client_id=" + client,
                type: 'get',
                success: function(response) {
                		data = JSON.parse(response);
                    if(data) {
                    		$('#id_language').val(data["language"])
                    		$('#id_trek').val(data["trek"])
                    }
                }
	    		})
	    }
	    
	    function getFilteredGuides() {
	    		var trek_status = document.getElementById("id_guide_filter").value;
	    		$.ajax({ 
	            url: "/guiderota/get_filtered_guides?trekking_status=" + trek_status,
	            type: 'get',
	            success: function(response) {
	            		data = JSON.parse(response);
	                if(data) {
	                		var $select = $('#id_guide')
	                		$select.empty()
	                		$select.append($("<option></option>").attr("value", '').text("---------"));
						$.each(data, function(key, value) {
							$select.append($("<option></option>")
									.attr("value", key).text(value));
						})	                		
	                }
	            }
	    		})
	    }
	    var d = document.getElementById("guiderota")
		d.className += "active"

    </script>

{% endblock %}

templates/bpos_guide_rota/guiderota_update.html
{% load crispy_forms_tags %}

	<form method="post" class="form" id='custom_dialog_form'>
		{% include 'common/error_field.html' %}
	  	{% csrf_token %}
	 	{% crispy form form.helper %}
	</form>
	