bpos_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bpos_proj import views
from bpos_proj.forms import LoginForm
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

admin.site.site_header = 'BPOS Settings'
admin.site.index_title = "Settings"
admin.site.site_title = "Administration"

urlpatterns = [
    url(r'^$', views.home, name='home-page'),
    url(r'^api/enquiry_data/$', views.get_enquiry_data, name='enquiry-page'),
    url(r'^login/$', auth_view.login, {'template_name': 'registration/login.html', 'authentication_form': LoginForm}, name="login"),
    url(r'^logout/$', auth_view.LogoutView.as_view(next_page=reverse_lazy('login')), name="logout"),
    url(r'^password_reset/$', auth_view.PasswordResetView.as_view(template_name='registration/password_reset.html'), name="password_reset"),
    url(r'^password_reset/done/$', auth_view.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_view.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name="password_reset_confirm"),
    url(r'^reset/done/$', auth_view.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name="password_reset_complete"),
    url(r'^admin/', admin.site.urls),
    url(r'^client-autocomplete/', login_required(views.ClientAutocomplete.as_view()), name="client-autocomplete"),
    url(r'^mgmtdata/', views.mgmtdata, name='mgmtdata'),
    url(r'^enquiries/', include('bpos_enquiries.urls')),
    url(r'^status/', include('bpos_status_report.urls')),
    url(r'^guiderota/', include('bpos_guide_rota.urls')),
    url(r'^flights/', include('bpos_flights.urls')),
    url(r'^payments/', include('bpos_payments.urls')),
    url(r'^hotels/', include('bpos_hotel_reservation.urls'))
]

bpos_status_report/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from bpos_status_report import views

urlpatterns = [
    url(r'^$', login_required(views.ClientList.as_view()), name="client-list"),
    url(r'udocstatus/$', login_required(views.update_docstatus), name="docstatus"),
    url(r'memberadd/$', login_required(views.create_member), name="member-add"),
    url(r'documentadd/$', login_required(views.create_document), name="document-add"),
    url(r'add/$', login_required(views.create_client), name="client-add"),
    url(r'document/(?P<pk>[-\w]+)/update/$', login_required(views.update_document), name="document-edit"),
    url(r'document/(?P<pk>[-\w]+)/delete/$', login_required(views.DocumentDelete.as_view()), name="document-delete"),
    url(r'member/(?P<pk>[-\w]+)/update/$', login_required(views.update_member), name="member-edit"),
    url(r'member/(?P<pk>[-\w]+)/delete/$', login_required(views.MemberDelete.as_view()), name="member-delete"),
    url(r'(?P<pk>[-\w]+)/update/$', login_required(views.update_client), name="client-update"),
    url(r'(?P<pk>[-\w]+)/delete/$', login_required(views.ClientDelete.as_view()), name="client-delete"),
    url(r'(?P<pk>[-\w]+)/$', login_required(views.ClientDetail.as_view()), name="client-detail"),
]

bpos_status_report/models.py
from django.db import models

from django.urls import reverse
from django.db.models.fields.related import ForeignKey

from bpos_agents.models import Agent
from bpos_enquiries.models import Enquiry

# Create your models here.
TITLE = (("mr", "Mr"), ("mrs", "Mrs"), ("ms", "Ms"), ("master", "Master"), ("miss", "Miss"))


class Client(models.Model):
    TYPE_CHOICES = (('fit', "FIT"), ('group', "Group"))
    TREK_CHOICES = (('bumdra', 'Bumdra'), ('dagala', 'Dagala'), ('other', 'Other'))
    LANGAUGE_CHOICES = (('french', "French"), ('chinese', 'Chinese'), ('japanese', 'Japanese'), ('other', 'Other'))
    OPTIONS_STATUS = (('0', ''), ('1', 'Passport On System'), ('2', 'Visa Applied For'), ('3', 'Visa Authorised'), ('4', 'Visa Sent To Client'))

    agent = models.ForeignKey(Agent, related_name="clients")
    type = models.CharField(max_length=50, blank=False, choices=TYPE_CHOICES, default='fit')
    group_name = models.CharField(max_length=100, blank=False)
    name = models.CharField(max_length=150, blank=False)
    pax = models.PositiveSmallIntegerField(default=1)
    arriving_date = models.DateField("Arriving On", null=False, blank=False)
    leaving_date = models.DateField("Leaving On", null=False, blank=False)
    entering_from = models.CharField("Entering From", max_length=100)
    leaving_to = models.CharField("Leaving To", max_length=100)
    trek = models.CharField(max_length=100, choices=TREK_CHOICES, blank=True)
    other_trek = models.CharField("Other Trek", max_length=300, blank=True)
    guide_notified = models.BooleanField("Guide Notified to Client?", blank=True, default=False)
    language_guide_needed = models.BooleanField("Language Guide Needed?", blank=True)
    language = models.CharField("Choose Language Needed", max_length=100, choices=LANGAUGE_CHOICES, blank=True)
    other_language = models.CharField("Other Language", max_length=100, blank=True)
    flight_status = models.CharField("Flight Status", max_length=100, blank=True)
    payment_status = models.CharField("Money Status", max_length=100, blank=True)
    hotel_status = models.CharField("Hotel Status", max_length=100, blank=True)
    visa_status = models.CharField("Visa Status", max_length=100, blank=True)
    guide = models.CharField("Guide", max_length=200, blank=True)
    is_archive = models.BooleanField(blank=True, default=0)
    status = models.CharField(max_length=2, blank=True, null=True, choices=OPTIONS_STATUS, default='0')
    enquiry = models.ForeignKey(Enquiry, related_name="clients", null=True, blank=True)

    def save(self, *args, **kwargs):
        self.name = str(self.agent) + " " + self.type + " - " + self.group_name
        if not self.flight_status:
            self.flight_status = "Not Yet Requested"

        if not self.hotel_status:
            self.hotel_status = "Not Yet Requested"

        return super(Client, self).save(*args, **kwargs)

    class Meta:
        ordering = ['arriving_date']

    def __str__(self):
        return "%s (id=%s)" % (self.name, self.id)

    def get_absolute_url(self):
        return reverse('client-detail', kwargs={'pk': self.id})


class Member(models.Model):
    client = ForeignKey(Client)
    full_name = models.CharField(max_length=200, null=False, blank=False)
    title = models.CharField(max_length=20, choices=TITLE)
    is_student = models.BooleanField("Is Student")

    def __str__(self):
        return "%s. %s (id: %s) " % (self.get_title_display(), self.full_name, self.id)


class Document(models.Model):
    DOC_TYPE_CHOICES = (('pass', "Passport"), ('v_info', "Visa Info"), ('stu', "Student ID"), ('visa', "Visa"))
    client = ForeignKey(Client)
    document_for = models.ForeignKey(Member)
    document_type = models.CharField("Document Type", max_length=30, choices=DOC_TYPE_CHOICES)
    comment = models.TextField(null=True, blank=True)
    visa_alert = models.BooleanField("Send Alert to Visas")
    ticket_alert = models.BooleanField("Send Alert to Ticketing")
    document = models.FileField(upload_to='documents/', blank=True)

bpos_status_report/views.py
# Create your views here.
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
import simplejson

from .models import Client, Member, Document
from .forms import ClientForm, ClientEditForm, MemberForm, DocumentForm


@permission_required('bpos_status_report.add_client')
def create_client(request):
    if request.method == 'POST':
        form = ClientForm(request.POST)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)
        return HttpResponse(simplejson.dumps(response))
    else:
        form = ClientForm()

    return render(request, 'bpos_status_report/status_add.html', {
        'form': form,
    })


@permission_required('bpos_status_report.change_client')
def update_client(request, pk):
    if request.method == 'POST':
        enquiry = get_object_or_404(Client, pk=pk)
        form = ClientEditForm(request.POST, instance=enquiry)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        enquiry = get_object_or_404(Client, pk=pk)
        form = ClientEditForm(instance=enquiry)

    return render(request, 'bpos_status_report/status_update.html', {
        'form': form,
    })


class ClientDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('bpos_status_report.delete_client')
    model = Client
    success_url = reverse_lazy("client-list")
    template_name = "common/delete_form.html"


class ClientList(PermissionRequiredMixin, ListView):
    permission_required = ('bpos_status_report.view_client')
    model = Client
    template_name = "bpos_status_report/status_list.html"

    def get_context_data(self, **kwargs):
        context = super(ClientList, self).get_context_data(**kwargs)
        return context


class ClientDetail(PermissionRequiredMixin, DetailView):
    permission_required = ('bpos_status_report.view_client')
    model = Client
    template_name = "bpos_status_report/status_detail.html"

    def get_context_data(self, **kwargs):
        context = super(ClientDetail, self).get_context_data(**kwargs)
        context['member_list'] = Member.objects.filter(client=context['object'].id).order_by("id")
        context['document_list'] = Document.objects.filter(client=context['object'].id).order_by("id")
        return context


@permission_required('bpos_status_report.add_member')
def create_member(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        response = {}
        if form.is_valid():
            form.save()
            response["status"] = "OK"
        else:
            response["status"] = "bad"
            response.update(form.errors)
        return HttpResponse(simplejson.dumps(response))
    else:
        '''Initialize the client value and disable others in view'''
        if request.GET['client']:
            form = MemberForm(initial={"client": request.GET['client']})
        else:
            form = MemberForm()

    return render(request, 'bpos_status_report/member/member_add.html', {
        'form': form,
    })


@permission_required('bpos_status_report.change_member')
def update_member(request, pk):
    if request.method == 'POST':
        member = get_object_or_404(Member, pk=pk)
        form = MemberForm(request.POST, instance=member)
        response = {}
        if form.is_valid():
            form.save()
            response["status"] = "OK"
        else:
            response["status"] = "bad"
            response.update(form.errors)
        return HttpResponse(simplejson.dumps(response))
    else:
        '''Initialize the client value and disable others in view'''
        member = get_object_or_404(Member, pk=pk)
        form = MemberForm(instance=member)

    return render(request, 'bpos_status_report/member/member_add.html', {
        'form': form,
    })


class MemberDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('bpos_status_report.delete_member')
    model = Member
    template_name = "common/delete_form.html"

    def post(self, request, *args, **kwargs):
        self.success_url = request.POST['parent_url']
        return self.delete(request, *args, **kwargs)


@permission_required('bpos_status_report.add_document')
def create_document(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES, label="Create Document")
        print(request.FILES)
        response = {}
        if form.is_valid():
            doc = form.save()
            return redirect(doc.client)

        else:
            response["status"] = "bad"
            response.update(form.errors)
        return HttpResponse(simplejson.dumps(response))
    else:
        '''Initialize the client value and disable others in view'''
        if request.GET['client']:
            form = DocumentForm(initial={"client": request.GET['client']}, label="Create Document")
        else:
            form = DocumentForm(label="Create Document")

    return render(request, 'bpos_status_report/document/document_add.html', {
        'form': form,
    })


@permission_required('bpos_status_report.change_document')
def update_document(request, pk):
    if request.method == 'POST':
        document = get_object_or_404(Document, pk=pk)
        form = DocumentForm(request.POST, request.FILES, instance=document, label="Update Document")
        response = {}
        if form.is_valid():
            doc = form.save()
            return redirect(doc.client)
        else:
            response["status"] = "bad"
            response.update(form.errors)
        return HttpResponse(simplejson.dumps(response))
    else:
        '''Initialize the client value and disable others in view'''
        document = get_object_or_404(Document, pk=pk)
        form = DocumentForm(instance=document, label="Update Document")

    return render(request, 'bpos_status_report/document/document_add.html', {
        'form': form,
    })


class DocumentDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('bpos_status_report.delete_document')
    model = Document
    template_name = "common/delete_form.html"

    def post(self, request, *args, **kwargs):
        self.success_url = request.POST['parent_url'] + "#visa_document"
        return self.delete(request, *args, **kwargs)


def update_docstatus(request):
    if request.method == 'POST':
        id = request.POST.get('client')
        status = request.POST.get('status')
        client = Client.objects.get(pk=id)
        if not status:
            status = 0
        client.status = status
        client.save()
        response = {"status": "done"}
    return HttpResponse(simplejson.dumps(response))

templates/bpos_status_report/add_hide.html
<script>
		function toggleHide() {
			if(document.getElementById('id_trek').options[document.getElementById('id_trek').selectedIndex].value == "other") {
				document.getElementById("div_id_other_trek").style.display = "inline";
			}
			else {
				document.getElementById("div_id_other_trek").style.display = "none";
			}
			
			if($('#id_language_guide_needed').is(":checked")) {
				document.getElementById("div_id_language").style.display = "inline";
			}
			else {
				document.getElementById("div_id_language").style.display = "none";
			}
			
			if(document.getElementById('id_language').options[document.getElementById('id_language').selectedIndex].value == "other") {
				document.getElementById("div_id_other_language").style.display = "inline";
			}
			else {
				document.getElementById("div_id_other_language").style.display = "none";
			}
		}

		window.onload = function() {
       		$('body').on('change', '#id_trek', toggleHide)
       		$('body').on('change', '#id_language_guide_needed', toggleHide)
       		$('body').on('change', '#id_language', toggleHide)
    	}
		
	</script>

templates/bpos_status_report/status_add.html
{% load crispy_forms_tags %}

{% block content %}
	<form method="post" class="form" id="custom_dialog_form" >
	  {% include 'common/error_field.html' %}
	  {% crispy form %}
	</form>
{% endblock %}

{% block footer %}
<script>
	$("#id_arriving_date").datepicker({ dateFormat: "yy-mm-dd" });
	$("#id_leaving_date").datepicker({ dateFormat: "yy-mm-dd" });
	
	//Run the field hide script when document is ready
	$( function() {
		toggleHide();
	})
</script>	
{% endblock %}

templates/bpos_status_report/status_detail.html
{% extends 'common/base.html' %}
{% load bpos_group_check %}

{% block header %}
	<style>
		.row {
			margin-bottom: 15px !important;
		}
		
		.tab-more-info {
			margin-bottom: 50px;
		}
		
	</style>
	    
{% endblock %}

{% block content %}
<div id="custom_main_content">
	<div class="col-md-12 lead"><h2>Client Summary</h2><hr /></div>
	<div class="row col-md-12">
		  <div class="col-md-2">Name</div>
		  <div class="col-md-3"><strong>{{ object.group_name }}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Flights</div>
		  <div class="col-md-3"><strong>{{ object.flight_status }}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Agent / Type</div>
		  <div class="col-md-3"><strong>{{ object.agent }} / {{ object.type }}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Hotels</div>
		  <div class="col-md-3"><strong>{{ object.hotel_status }}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Pax</div>
		  <div class="col-md-3"><strong>{{ object.pax }}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Payment</div>
		  <div class="col-md-3"><strong>{{ object.payment_status }}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Arriving On</div>
		  <div class="col-md-3"><strong>{{ object.arriving_date }}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Visa</div>
		  <div class="col-md-3"><strong>{{ object.get_status_display }}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">leaving On</div>
		  <div class="col-md-3"><strong>{{ object.leaving_date }}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Guide</div>
		  <div class="col-md-3"><strong>{{ object.guide }}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Entering From / Leqving To</div>
		  <div class="col-md-3"><strong>{{ object.entering_from }} / {{ object.leaving_to }}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Language</div>
		  <div class="col-md-3"><strong>{% if object.language and object.language != 'other' %} {{ object.language }} {% elif object.other_language %} {{ object.other_language }} {% else %} {% endif %}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Trek</div>
		  <div class="col-md-3"><strong>{% if object.trek and object.trek != 'other' %} {{ object.trek }} {% elif object.other_trek %} {{ object.other_trek }} {% else %} {% endif %}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Guide Notified To Client</div>
		  <div class="col-md-3"><strong>{% if object.guide_notified %} Yes {% else %} No {% endif %}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2"></div>
		  <div class="col-md-3"></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-3">
				<a href="/status" class="btn btn-info"> &lt;&lt; Back To List </a>
				{% if request.user|has_group:"London" or request.user.is_superuser%}
		  		<a class="btn btn-primary edit_client_button" id="{{ object.id }}"> Edit Client</a>
		  		{% endif %}
		  </div>
	</div>
</div>

<div class="tab-more-info">
    <ul class="nav nav-tabs">
        <li class="active"><a data-toggle="tab" href="#group_member">Group Members</a></li>
        <li><a data-toggle="tab" href="#itinerary">Itinerary</a></li>
        <li><a data-toggle="tab" href="#trip_summary">Trip Summary</a></li>
        <li><a data-toggle="tab" href="#trip_confirmation">Trip Confirmation</a></li>
        <li><a data-toggle="tab" href="#visa_document">Visa Documents</a></li>
        <li><a data-toggle="tab" href="#trip_for_guide">Trip Summary for Guide</a></li>
    </ul>
    <div class="tab-content">
        <div id="group_member" class="tab-pane fade in active">
        		<div class="row col-md-12">
        			<h3>Members {% if request.user|has_group:"London" or request.user.is_superuser%}<a id="{{ object.id }}" class="btn btn-success create_member_button" style="float: right;">Add Member</a>{% endif %}</h3>
        		</div>
        		<div class="col-md-10">
		        	<table class="table table-hover table-striped table-bordered" id="member_list">
					<thead class="thead-dark">
						<tr>
							<th>ID</th>
							<th>Title</th>
							<th>Full Name</th>
							<th>Is Student</th>
							{% if request.user|has_group:"London" or request.user.is_superuser%}
							<th class="col-md-1"></th>
							<th class="col-md-1"></th>
							{% endif %}
						</tr>
					</thead>
					<tbody>
					{% for m in member_list %}
						<tr>
							<td> {{ m.id }}</td>
							<td> {{ m.get_title_display }} </a></td>
							<td> {{ m.full_name }} </td>	
							<td> {% if m.is_student %} <i class="fas fa-check"></i> {% else %} {% endif %} </td>
							{% if request.user|has_group:"London" or request.user.is_superuser%}
							<td> <a id="{{ m.id }}" class='edit_member_button'><i class="fas fa-edit text-info"></i></a> </td>
							<td> <a id="{{ m.id }}" href="/status/member/{{m.id}}/delete/" class='delete_member_button'><i class="far fa-trash-alt"></i></a> </td>
							{% endif %}
						</tr>
					{% empty %}
						<tr><td></td><td></td><td></td><td></td>
						{% if request.user|has_group:"London" or request.user.is_superuser%}
						<td></td><td></td>
						{% endif %}</tr>
					{% endfor %}
					</tbody>
				</table>
            </div>
        </div>
        <div id="itinerary" class="tab-pane fade">
            <h3>Itinerary</h3>
        </div>
        <div id="trip_summary" class="tab-pane fade">
            <h3>Trip Summary</h3>
        </div>
        <div id="trip_confirmation" class="tab-pane fade">
            <h3>Trip Confirmation</h3>
        </div>
        <div id="visa_document" class="tab-pane fade">
        	   <div class="row col-md-12">
        	   		{% if request.user|has_group:"London" or request.user|has_group:"Visas" or request.user.is_superuser%} 
        			<h4>Edit Status </h4><hr />
        			<div class='col-md-1'><h4>Status</h4></div>
        			<div class='col-md-4'>
        				{% if request.user.is_superuser %}
        				<select class="select form-control" id='id_docstatus'>
        					<option value='1'>Passport On System</option>
        					<option value='2'>Visa Applied For</option>
        					<option value='3'>Visa Authorised</option>
        					<option value='4'>Visa Sent To Client</option>
        				</select>
        				{% elif request.user|has_group:"London" %}
        				<select class="select form-control" id='id_docstatus'>
        					<option value='1'>Passport On System</option>
        					<option value='4'>Visa Sent To Client</option>
        				</select>
        				{% elif request.user|has_group:"Visas" %}
        				<select class="select form-control" id='id_docstatus'>
        					<option value='2'>Visa Applied For</option>
        					<option value='3'>Visa Authorised</option>
        				</select>
        				{% else %}
        				{% endif %}
        			</div>	
        			<div class='col-md-1'><a id="{{ object.id }}" class="btn btn-primary update_docstatus_button">Save</a></div>
        			{% endif %}
        		</div>
        		
            <div class="row col-md-12">
        			<h3>Visa Document 
        				{% if request.user|has_group:"London" or request.user|has_group:"Visas" or request.user.is_superuser%} 
        				<a id="{{ object.id }}" class="btn btn-success create_document_button" style="float: right;" href="/status/documentadd/?client={{object.id}}">Add Document</a>
        				{% endif %}</h3>
        				<hr />
        		</div>
        		<div class="col-md-12">
		        	<table class="table table-hover table-striped table-bordered" id="document_list">
					<thead class="thead-dark">
						<tr>
							<th class="col-md-2">Document For</th>
							<th class="col-md-2">Document Type</th>
							<th class="col-md-1">Document Uploaded?</th>
							<th class="col-md-5">Comments</th>
							{% if request.user|has_group:"London" or request.user|has_group:"Visas" or request.user.is_superuser %}
							<th class="col-md-1"></th>
							<th class="col-md-1"></th>
							{% endif %}
						</tr>
					</thead>
					<tbody>
					{% for m in document_list %}
						<tr>
							<td> {{ m.document_for }}</td>
							<td> {{ m.get_document_type_display }} </a></td>
							<td> {{ m.document }} </td>	
							<td> {{ m.comment }} </td>
							{% if request.user|has_group:"London" or request.user|has_group:"Visas" or request.user.is_superuser%}
							<td> <a id="{{ m.id }}" class='edit_document_button' href="/status/document/{{m.id}}/update/"><i class="fas fa-edit text-info"></i></a> </td>
							<td> <a id="{{ m.id }}" href="/status/document/{{m.id}}/delete/" class='delete_document_button'><i class="far fa-trash-alt"></i></a> </td>
							{% endif %}
						</tr>
					{% empty %}
						<tr><td></td><td></td><td></td><td></td>{% if request.user|has_group:"London" or request.user|has_group:"Visas" or request.user.is_superuser%}<td></td><td></td>{% endif %}</tr>
					{% endfor %}
					</tbody>
				</table>
            </div>
        </div>
        <div id="trip_for_guide" class="tab-pane fade">
            <h3>Trip Summary for Guide</h3>
        </div>
    </div>
</div>

{% endblock %}

{% block footer %}	
	{% include 'bpos_status_report/add_hide.html' %}
    {% include 'common/create_dialog.html' %}
    <script type="text/javascript"> window.CSRF_TOKEN = "{{ csrf_token }}"; </script>
    <script>
	    $(function() {
	        $('.edit_client_button').on('click', function() { 
	            url = "/status/" + $(this).context.id + "/update/"
	            $('#dialog-modal').load(url);
	            init_dialog("Update Client", url, "#custom_dialog_form", "Update Client")
	        });
	        
	        $('.create_member_button').on('click', function() { 
	            $('#dialog-modal').load('/status/memberadd/?client=' + $(this).context.id);
	            init_dialog("Add Client Members", "memberadd/", "#custom_dialog_form", "Create Member")
	        });

	        $('.edit_member_button').on('click', function() { 
	            url = "/status/member/" + $(this).context.id + "/update/"
	            $('#dialog-modal').load(url);
	            init_dialog("Update Member", url, "#custom_dialog_form", "Update Member")
	        });
	        
	        $('.update_docstatus_button').on('click', function() { 
	            $.ajax({ 
                        url: "/status/udocstatus/",
                        data: {
                        		client: $(this).context.id, 
                        		status: document.getElementById('id_docstatus').options[document.getElementById('id_docstatus').selectedIndex].value,
                        		csrfmiddlewaretoken: '{{ csrf_token }}'
                        	},
                        type: 'post',
                        // if successful print response
                        success: function(response) {
                        	console.log(location)
                        	location['href'] = location['href'] + "#visa_document"
                        	location.reload(true);
                        }
	            })
	        });
	        
	    });
	    
	    $('body').on('onload', set_docstatus_value())
	    		
	    function set_docstatus_value() {
	    		document.getElementById('id_docstatus').value={{ object.status }};
	    }

	    var d = document.getElementById("status")
		d.className += "active"

    </script>
{% endblock %}

templates/bpos_status_report/status_update.html
{% load crispy_forms_tags %}

{% block content %}
	<form method="post" class="form" id='custom_dialog_form'>
		{% include 'common/error_field.html' %}
	 	{% crispy form form.helper %}
	</form>
{% endblock %}

{% block footer %}
<script>
	$("#id_arriving_date").datepicker({ dateFormat: "yy-mm-dd" });
	$("#id_leaving_date").datepicker({ dateFormat: "yy-mm-dd" });
	
	//Run the field hide script when document is ready
	$( function() {
		toggleHide();
	})

	var d = document.getElementById("status")
	d.className += "active"
</script>	
{% endblock %}