bpos_hotel_reservation/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from bpos_hotel_reservation import views

urlpatterns = [
    url(r'^$', login_required(views.HotelList.as_view()), name="hotel-list"),
    url(r'roomadd/$', login_required(views.create_room), name="room-add"),
    url(r'add/$', login_required(views.create_hotel), name="hotel-add"),
    url(r'roomupdate/(?P<pk>[-\w]+)/update/$', login_required(views.update_room), name="room-update"),
    url(r'roomupdate/(?P<pk>[-\w]+)/delete/$', login_required(views.RoomDelete.as_view()), name="room-delete"),
    url(r'(?P<pk>[-\w]+)/update/$', login_required(views.update_hotel), name="hotel-update"),
    url(r'(?P<pk>[-\w]+)/delete/$', login_required(views.delete_hotel), name="hotel-delete"),
    url(r'(?P<pk>[-\w]+)/$', login_required(views.HotelDetail.as_view()), name="hotel-detail"),
    url(r'^get_filtered_hotels', login_required(views.get_filtered_hotels), name="hotel-get_filtered_hotels")
]

bpos_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bpos_proj import views
from bpos_proj.forms import LoginForm
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required

admin.site.site_header = 'BPOS Settings'
admin.site.index_title = "Settings"
admin.site.site_title = "Administration"

urlpatterns = [
    url(r'^$', views.home, name='home-page'),
    url(r'^api/enquiry_data/$', views.get_enquiry_data, name='enquiry-page'),
    url(r'^login/$', auth_view.login, {'template_name': 'registration/login.html', 'authentication_form': LoginForm}, name="login"),
    url(r'^logout/$', auth_view.LogoutView.as_view(next_page=reverse_lazy('login')), name="logout"),
    url(r'^password_reset/$', auth_view.PasswordResetView.as_view(template_name='registration/password_reset.html'), name="password_reset"),
    url(r'^password_reset/done/$', auth_view.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
        name="password_reset_done"),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_view.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name="password_reset_confirm"),
    url(r'^reset/done/$', auth_view.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
        name="password_reset_complete"),
    url(r'^admin/', admin.site.urls),
    url(r'^client-autocomplete/', login_required(views.ClientAutocomplete.as_view()), name="client-autocomplete"),
    url(r'^mgmtdata/', views.mgmtdata, name='mgmtdata'),
    url(r'^enquiries/', include('bpos_enquiries.urls')),
    url(r'^status/', include('bpos_status_report.urls')),
    url(r'^guiderota/', include('bpos_guide_rota.urls')),
    url(r'^flights/', include('bpos_flights.urls')),
    url(r'^payments/', include('bpos_payments.urls')),
    url(r'^hotels/', include('bpos_hotel_reservation.urls'))
]

bpos_hotel_reservation/models.py
from django.db import models
from bpos_status_report.models import Client
from bpos_towns.models import Town
from bpos_hotels.models import Hotel, HOTEL_TYPE_CHOICES

FOOD_OPTIONS = (('1', 'Bed and Breakfast'), ('2', 'Bed, Breakfast and Dinner'), ('3', 'Full Board'))
ROOM_TYPE = (('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'))
ROOM_CAT = (
    ('1', 'Superior'),
    ('2', 'Deluxe'),
    ('3', 'Luxury'),
    ('4', 'Junior Suite'),
    ('5', 'Suite'),
    ('6', 'One Bed Villa'),
    ('7', 'Two Bed Villa'),
    ('8', 'Other')
)
ROOM_STATUS = (('1', 'Not Yet Requested'), ('2', 'Requested'), ('3', 'Waiting'), ('4', 'Confirmed'))


# Create your models here.
class HotelReservation(models.Model):
    client = models.ForeignKey(Client)
    town = models.ForeignKey(Town)
    arriving_on = models.CharField("Arriving On", max_length=20)
    leaving_on = models.CharField("Leaving On", max_length=20)
    hotel_type = models.CharField(max_length=100, choices=HOTEL_TYPE_CHOICES)
    hotel_name = models.ForeignKey(Hotel)
    food_option = models.CharField(max_length=100, choices=FOOD_OPTIONS, null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    is_backup = models.BooleanField("Is Backup")

    def __str__(self):
        return str(self.hotel_name)


class Room(models.Model):
    hotel = models.ForeignKey(HotelReservation)
    date = models.DateField()
    room_type = models.CharField("Room Type", choices=ROOM_TYPE, max_length=10)
    room_category = models.CharField("Room Category", choices=ROOM_CAT, max_length=10)
    other_category = models.CharField("Other Room Category", max_length=100, blank=True, null=True)
    quantity = models.PositiveSmallIntegerField("Quantity")
    extra_bed = models.CharField("Extra Bed", max_length=100, null=True, blank=True)
    room_status = models.CharField("Room Status", choices=ROOM_STATUS, max_length=10)
    is_backup = models.BooleanField("Is backup")

    def __str__(self):
        return str(self.hotel) + "(" + str(self.date) + ")"

bpos_flights/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import DeleteView

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Flight, FlightGroup
from .forms import FlightForm, FlightGroupForm
from bpos_status_report.models import Member, Client

from dateutil.relativedelta import relativedelta
import simplejson


@permission_required('bpos_flights.add_flight')
def create_flight(request):
    if request.method == 'POST':
        form = FlightForm(request.POST)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()

        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        # Initialize the client value and disable others in view
        if request.GET['client']:
            form = FlightForm(initial={"client": request.GET['client']})
        else:
            form = FlightForm()
    return render(request, 'bpos_flights/passenger/passenger_add.html', {
        'form': form,
    })


@permission_required('bpos_flights.change_flight')
def update_flight(request, pk):
    if request.method == 'POST':
        flights = get_object_or_404(Flight, pk=pk)
        form = FlightForm(request.POST, instance=flights)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        flights = get_object_or_404(Flight, pk=pk)
        form = FlightForm(instance=flights)

    return render(request, 'bpos_flights/passenger/passenger_update.html', {
        'form': form,
    })


class FlightDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('bpos_flights.delete_flight')
    model = Flight
    template_name = "common/delete_form.html"

    def post(self, request, *args, **kwargs):
        self.success_url = request.POST['parent_url']
        return self.delete(request, *args, **kwargs)


class FlightList(ListView):
    model = FlightGroup
    template_name = "bpos_flights/flights_list.html"

    def get_context_data(self, **kwargs):
        context = super(FlightList, self).get_context_data(**kwargs)
        for a in context['object_list']:
            fl = Flight.objects.filter(client=a.client).values("ttl").order_by("-ttl")[:1]
            if fl:
                a.ttl = fl[0]['ttl']
        return context


class PassengerList(ListView):
    model = Flight
    template_name = "bpos_flights/passenger/passenger_list.html"

    def get_context_data(self, **kwargs):
        context = super(PassengerList, self).get_context_data(**kwargs)
        pk_id = self.kwargs.get('pk', None)
        if pk_id:
            context['client'] = FlightGroup.objects.get(pk=pk_id)
            context['object_list'] = context['object_list'].filter(client=context['client'].client)
            for a in context['object_list']:
                if(relativedelta(a.date, a.dob).years < 12):
                    a.is_child = 1
                else:
                    a.is_child = 0
        else:
            context['client'] = None
            context['object_list'] = None

        return context


class FlightDetail(DetailView):
    model = Flight
    template_name = "bpos_flights/flights_detail.html"

    def get_context_data(self, **kwargs):
        context = super(FlightDetail, self).get_context_data(**kwargs)
        return context


@permission_required('bpos_flights.add_flightgroup')
def create_flightgroup(request):
    if request.method == 'POST':
        form = FlightGroupForm(request.POST)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        form = FlightGroupForm()

    return render(request, 'bpos_flights/flights_add.html', {
        'form': form,
    })


@permission_required('bpos_flights.change_flightgroup')
def update_flightgroup(request, pk):
    if request.method == 'POST':
        flights = get_object_or_404(FlightGroup, pk=pk)
        form = FlightGroupForm(request.POST, instance=flights)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        flights = get_object_or_404(FlightGroup, pk=pk)
        form = FlightGroupForm(instance=flights)

    return render(request, 'bpos_flights/flights_update.html', {
        'form': form,
    })


# Get the filtered list of clients for on the client filter
def get_filtered_clients(request):
    response = {}
    if request.GET.get('trekking_status'):
        client_obj = request.GET.get('trekking_status')
        if client_obj == '0':
            result = Client.objects.filter().order_by("id")
        else:
            result = Client.objects.filter(trekking_status=client_obj).order_by("id")
    else:
        result = Client.objects.filter().order_by("id")

    for a in result:
        response[a.id] = a.__str__()

    return HttpResponse(simplejson.dumps(response))


# Get the filtered list of passengers based on the client filter
def get_filtered_passengers(request):
    response = {}
    if request.GET.get('client_filter'):
        client_obj = request.GET.get('client_filter')
        if client_obj == '0':
            result = Member.objects.filter().order_by("id")
        else:
            result = Member.objects.filter(client=client_obj).order_by("id")
    else:
        result = Member.objects.filter().order_by("id")

    for a in result:
        response[a.id] = a.__str__()

    return HttpResponse(simplejson.dumps(response))


# Get the Passenger Info
def get_passenger_info(request):
    response = {}
    if request.GET.get('pass_id'):
        client_name = request.GET.get('pass_id')
        result = Member.objects.filter(pk=client_name).values("title", "full_name")
        response['title'] = result[0]['title']
        response['full_name'] = result[0]['full_name']

    return HttpResponse(simplejson.dumps(response))

bpos_hotel_reservation/views.py
# Create your views here.
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic.edit import DeleteView
import simplejson

from .models import HotelReservation, Room
from .forms import RoomForm, HotelForm
from bpos_hotels.models import Hotel


@permission_required('bpos_hotel_reservation.add_hotelreservation')
def create_hotel(request):
    if request.method == 'POST':
        form = HotelForm(request.POST)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)
        return HttpResponse(simplejson.dumps(response))
    else:
        form = HotelForm()

    return render(request, 'bpos_hotel_reservation/hotels_add.html', {
        'form': form,
    })


@permission_required('bpos_hotel_reservation.change_hotelreservation')
def update_hotel(request, pk):
    if request.method == 'POST':
        enquiry = get_object_or_404(HotelReservation, pk=pk)
        form = HotelForm(request.POST, instance=enquiry)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        enquiry = get_object_or_404(HotelReservation, pk=pk)
        form = HotelForm(instance=enquiry)

    return render(request, 'bpos_hotel_reservation/hotels_update.html', {
        'form': form,
    })


@permission_required('bpos_hotel_reservation.delete_hotelreservation')
def delete_hotel(request, pk):
    # Delete logic
    response = {"status": "OK"}
    return HttpResponse(simplejson.dumps(response))


class HotelList(ListView):
    model = HotelReservation
    template_name = "bpos_hotel_reservation/hotels_list.html"

    def get_context_data(self, **kwargs):
        context = super(HotelList, self).get_context_data(**kwargs)
        return context


class HotelDetail(DetailView):
    model = HotelReservation
    template_name = "bpos_hotel_reservation/hotels_detail.html"

    def get_context_data(self, **kwargs):
        context = super(HotelDetail, self).get_context_data(**kwargs)
        context['room_list'] = Room.objects.filter(hotel=context['object'].id).order_by("id")
        return context


@permission_required('bpos_hotel_reservation.add_room')
def create_room(request):
    if request.method == 'POST':
        form = RoomForm(request.POST)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)
        return HttpResponse(simplejson.dumps(response))
    else:
        # Initialize the client value and disable others in view
        if request.GET['hotel']:
            form = RoomForm(initial={"hotel": request.GET['hotel']})
        else:
            form = RoomForm()

    return render(request, 'bpos_hotel_reservation/room_add.html', {
        'form': form,
    })


@permission_required('bpos_hotel_reservation.change_room')
def update_room(request, pk):
    if request.method == 'POST':
        enquiry = get_object_or_404(Room, pk=pk)
        form = RoomForm(request.POST, instance=enquiry)
        response = {}
        if form.is_valid():
            response["status"] = "OK"
            form.save()
        else:
            response["status"] = "bad"
            response.update(form.errors)

        return HttpResponse(simplejson.dumps(response))
    else:
        enquiry = get_object_or_404(Room, pk=pk)
        form = RoomForm(instance=enquiry)

    return render(request, 'bpos_hotel_reservation/room_add.html', {
        'form': form,
    })


class RoomDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('bpos_hotel_reservation.delete_room')
    model = Room
    template_name = "common/delete_form.html"

    def post(self, request, *args, **kwargs):
        self.success_url = request.POST['parent_url']
        return self.delete(request, *args, **kwargs)


# Get the filtered list of guides based on the guide filter
def get_filtered_hotels(request):
    response = {}
    hotel_type = request.GET.get('hotel_type')
    town = request.GET.get('town')
    if hotel_type and town:
            result = Hotel.objects.filter(type=hotel_type, town=town).order_by("id")
    elif town:
            result = Hotel.objects.filter(town=town).order_by("id")
    elif hotel_type:
            result = Hotel.objects.filter(type=hotel_type).order_by("id")
    else:
        result = Hotel.objects.filter().order_by("id")

    for a in result:
        response[a.id] = a.__str__()

    return HttpResponse(simplejson.dumps(response))

templates/bpos_hotel_reservation/hotels_add.html
{% load crispy_forms_tags %}

	<form method="post" class="form" id="custom_dialog_form" >
	  {% include 'common/error_field.html' %}
	 {% crispy form form.helper%}
	</form>

<script>
	$("#id_arriving_on").datepicker({ dateFormat: "yy-mm-dd" });
	$("#id_leaving_on").datepicker({ dateFormat: "yy-mm-dd" });
	
</script>

templates/bpos_hotel_reservation/hotels_detail.html
{% extends 'common/base.html' %}
{% load bpos_group_check %}

{% block header %}
	<style>
		.row {
			margin-bottom: 15px !important;
		}
		
		.tab-more-info {
			margin-bottom: 50px;
		}
		
	</style>
	    
{% endblock %}

{% block content %}
<div id="custom_main_content">
	<div class="row col-md-12">
		  <div class="col-md-9"><h3>Hotels</h3><hr /></div>
		  <div class="col-md-3">
				<a href="/hotels" class="btn btn-info"> &lt;&lt; Back To List </a>
				{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser %} 
		  		<a class="btn btn-primary edit_hotel_button" id="{{ object.id }}"> Edit Hotel</a>
		  		{% endif %}
		  </div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-5"><h3></h3></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-5"><h3></h3></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Client</div>
		  <div class="col-md-3"><strong>{{ object.client }}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Arriving On</div>
		  <div class="col-md-3"><strong>{{ object.arriving_on }}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Town</div>
		  <div class="col-md-3"><strong>{{ object.town }}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Leaving On</div>
		  <div class="col-md-3"><strong>{{ object.leaving_on }}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Hotel Name</div>
		  <div class="col-md-3"><strong>{{ object.hotel_name}}</strong></div>
		  <div class="col-md-2"></div>
		  <div class="col-md-2">Notes</div>
		  <div class="col-md-3"><strong>{{ object.notes }}</strong></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Hotel Type </div>
		  <div class="col-md-3"><strong>{{ object.hotel_type }}</strong></div>
		  <div class="col-md-2"></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Food Option</div>
		  <div class="col-md-3"><strong>{{ object.get_food_option_display }}</strong></div>
		  <div class="col-md-2"></div>
	</div>
	<div class="row col-md-12">
		  <div class="col-md-2">Is Backup</div>
		  <div class="col-md-3">{% if object.is_backup %} Yes {% else %} No {% endif %}</div>
		  <div class="col-md-2"></div>
	</div>
		
	<div class="row col-md-12" style="height: 15px;">
	</div>
	<div class="row col-md-12">
		  <div class="col-md-4"><h4>Rooms</h4></div>
		  <div class="col-md-2"> </div>
		  <div class="col-md-4"></div>
		  <div class="col-md-2">
		  	{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser %} 
		  	<a id="{{ object.id }}" class="btn btn-success create_room_button" style="float: right;">Add New Room</a>
			{% endif %}
		  </div>
	</div>
	<div class="row col-md-12">
		  	<table class="table table-hover table-striped table-bordered" id="extra_list">
					<thead class="thead-dark">
						<tr>
							<th class="col-md-2">Date</th>
							<th class="col-md-2">Room Type</th>
							<th class="col-md-3">Room Category</th>
							<th class="col-md-1">Quantity </th>
							<th class="col-md-3">Room Status</th>
							<th class="col-md-1">backup? </th>
							{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser %} 
							<th class="col-md-1"> </th>
							<th class="col-md-1"> </th>
							{% endif %}
						</tr>
					</thead>
					<tbody>
					{% for m in room_list %}
						<tr>
							<td> {{ m.date }}</td>
							<td> {{ m.get_room_type_display }} </td>
							<td> {% if m.other_category %} {{ m.other_category }} {% else %} {{ m.get_room_category_display }} {% endif %} </td>
							<td> {{ m.quantity }} </td>
							<td> {{ m.get_room_status_display }} </td>
							<td> {% if m.is_backup %} Yes {% else %} No {% endif %} </td>
							{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser %} 
							<td> <a id="{{ m.id }}" class='edit_room_button'><i class="fas fa-edit text-info"></i></a> </td>
							<td> <a id="{{ m.id }}" class='delete_room_button' href="/hotels/roomupdate/{{m.id}}/delete/"><i class="far fa-trash-alt"></i></a> </td>
							{% endif %}
						</tr>
					{% empty %}
						<tr><td></td><td></td><td></td><td></td><td></td><td></td>
						{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser %} 
						<td></td><td></td>
						{% endif %}
						</tr>
					{% endfor %}
					</tbody>
				</table>
		  </div>				
</div>

{% endblock %}

{% block footer %}	
	{% include 'bpos_status_report/add_hide.html' %}
    {% include 'common/create_dialog.html' %}
    {% include 'bpos_hotel_reservation/room_add_hide.html' %}
    <script>
	    $(function() {
	        $('.edit_hotel_button').on('click', function() { 
	            url = "/hotels/" + $(this).context.id + "/update/"
	            $('#dialog-modal').load(url);
	            init_dialog("Update Hotel", url, "#custom_dialog_form", "Update Hotel")
	        });
	        
	        $('.create_room_button').on('click', function() { 
	            $('#dialog-modal').load('/hotels/roomadd/?hotel=' + $(this).context.id);
	            init_dialog("Add Room", "roomadd/", "#custom_dialog_form", "Create Room")
	        });
	        
	        $('.edit_room_button').on('click', function() { 
	            url = "/hotels/roomupdate/" + $(this).context.id + "/update/"
	            $('#dialog-modal').load(url);
	            init_dialog("Update Room", url, "#custom_dialog_form", "Update Room")
	        });
	        
	    });
	    
	    function getFilteredHotels() {
	    		var town = document.getElementById("id_town").value;
	    		var hotel_type = document.getElementById("id_hotel_type").value;
	    		
	    		$.ajax({ 
	            url: "/hotels/get_filtered_hotels?town=" + town + "&hotel_type=" + hotel_type,
	            type: 'get',
	            success: function(response) {
	            		data = JSON.parse(response);
	                if(data) {
	                		var $select = $('#id_hotel_name')
	                		$select.empty()
	                		$select.append($("<option></option>").attr("value", '').text("---------"));
						$.each(data, function(key, value) {
							$select.append($("<option></option>")
									.attr("value", key).text(value));
						})	                		
	                }
	            }
	    		})
		}

		var d = document.getElementById("hotels")
		d.className += "active"

    </script>
{% endblock %}

templates/bpos_hotel_reservation/hotels_list.html
{% extends 'common/base.html' %}
{% load staticfiles %}
{% load bpos_group_check %}

{% block header %}
    <link href="{% static 'datatables/DataTables-1.10.16/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css" rel="stylesheet">
{% endblock %}

{% block content %}
	<h2>Hotels
		{% if request.user|has_group:"London" or request.user|has_group:"Reservations" or request.user|has_group:"General Manager" or request.user.is_superuser %} 
			<a id='create_hotel_button' class="btn btn-success" style="float: right;"> Add New </a>
		{% endif %}
	</h2>
	<hr />
	
	<div class="table-responsive" style="clear: both;">  
		<table border="0" cellspacing="5" cellpadding="5">
       		 <tbody>
       		 	<tr>
     		       <td>Clients &emsp;</td>
   		           <td>
	   		           <select id="client-list" name="client-list" class="select form-control input-sm"></select>
   		           </td>
               </tr>
    			</tbody>
    		</table>
    		<br />
		<table class="table table-hover" id="hotel_list">
			<thead class="thead-light">
				<tr>
					<th>Client</th>
					<th>Pax</th>
					<th>Arriving On</th>
					<th>Leaving On</th>
					<th>Towns and Hotels</th>
				</tr>
			</thead>
			<tbody>
			{% for a in object_list %}
				<tr>
					<td> {{ a.client }} </td>
					<td> {{ a.pax }} </td>
					<td> {{ a.arriving_on }}</td>
					<td> {{ a.leaving_on }}</td>
					<td> <a href="/hotels/{{ a.id }}/"> Towns and Hotels </a></td>	
				</tr>
			{% empty %}
				<tr><td></td><td></td><td></td><td></td><td></td></tr>
			{% endfor %}
			</tbody>
		</table>
	</div>

{% endblock %}

{% block footer %}	
	{% include 'bpos_hotel_reservation/gr_list_datatable.html' %}
    {% include 'common/create_dialog.html' %}
	
    <script>
	    $(function() {
	        $('#create_hotel_button').on('click', function() { 
	            $('#dialog-modal').load('/hotels/add/');
	            init_dialog("Create a New Hotel", "add/", "#custom_dialog_form", "Create Hotel")
	            
	        });
	        
	        $('.edit_flight').on('click', function() { 
	            url = "/flights/" + $(this).context.id + "/update/"
	            $('#dialog-modal').load(url);
	            init_dialog("Update Flight Group", url, "#custom_dialog_form", "Update Flight Group")
	        });
	        
	    });
	    
	    function getFilteredHotels() {
	    		var town = document.getElementById("id_town").value;
	    		var hotel_type = document.getElementById("id_hotel_type").value;
	    		
	    		$.ajax({ 
	            url: "/hotels/get_filtered_hotels?town=" + town + "&hotel_type=" + hotel_type,
	            type: 'get',
	            success: function(response) {
	            		data = JSON.parse(response);
	                if(data) {
	                		var $select = $('#id_hotel_name')
	                		$select.empty()
	                		$select.append($("<option></option>").attr("value", '').text("---------"));
						$.each(data, function(key, value) {
							$select.append($("<option></option>")
									.attr("value", key).text(value));
						})	                		
	                }
	            }
	    		})
    		}
    		var d = document.getElementById("hotels")
			d.className += "active"
    </script>

{% endblock %}

templates/bpos_hotel_reservation/hotels_update.html
{% load crispy_forms_tags %}

	<form method="post" class="form" id='custom_dialog_form'>
		{% include 'common/error_field.html' %}
	  	{% csrf_token %}
	 	{% crispy form form.helper %}
	</form>
	
	<script>
		$("#id_la_date").datepicker({ dateFormat: "yy-mm-dd" });
		$("#id_arriving_on").datepicker({ dateFormat: "yy-mm-dd" });
		$("#id_leaving_on").datepicker({ dateFormat: "yy-mm-dd" });
		
	</script>
	

templates/bpos_hotel_reservation/room_add.html
{% load crispy_forms_tags %}

{% block content %}
	<form method="post" class="form" id="custom_dialog_form" >
	  {% include 'common/error_field.html' %}
	 {% crispy form form.helper%}
	</form>
	
	<script>
		$("#id_date").datepicker({ dateFormat: "yy-mm-dd" });
		//Disable other options
		$( "#id_hotel option:not(:selected)" ).prop('disabled',true);
		
		$( function() {
			toggleHide();
		})
	</script>
{% endblock %}